version: '3'
services:
    nginx:
      container_name: nginx
      image: nginx
      ports:
        - "80:80"
#      volumes:
      #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      restart: always
      networks:
        - ironman-net

networks:
  ironman-net:
    driver: bridge
